package com.example.vocabuilder.ui.util

import androidx.compose.runtime.compositionLocalOf

data class UiStrings(
    val appName: String,
    val search: String,
    val closeSearch: String,
    val clear: String,
    val importWords: String,
    val importWordBookJson: String,
    val settings: String,
    val allWords: String,
    val wordBook: String,
    val searchWords: String,
    val noWords: String,
    val noMatching: String,
    val tapPlusToAdd: String,
    val tryDifferentSearch: String,
    val review: String,
    val quiz: String,
    val stats: String,
    val learned: String,
    val addWord: String,
    val editWord: String,
    val wordTerm: String,
    val definitionTrans: String,
    val exampleSentence: String,
    val categoryOptional: String,
    val notesOptional: String,
    val save: String,
    val cancel: String,
    val delete: String,
    val back: String,
    val flashcardReview: String,
    val tapToReveal: String,
    val howWell: String,
    val forgot: String,
    val hard: String,
    val good: String,
    val easy: String,
    val skip: String,
    val allCaughtUp: String,
    val noWordsToReview: String,
    val reviewComplete: String,
    val known: String,
    val reviewAgain: String,
    val takeQuiz: String,
    val goBack: String,
    val notEnoughWords: String,
    val needAtLeast4: String,
    val question: String,
    val score: String,
    val quizComplete: String,
    val viewResults: String,
    val retryQuiz: String,
    val nextQuestion: String,
    val finishQuiz: String,
    val whatIsMeaning: String,
    val excellent: String,
    val greatJob: String,
    val goodEffort: String,
    val keepPracticing: String,
    val tryAgain: String,
    val backToHome: String,
    val statistics: String,
    val totalWords: String,
    val learnedWords: String,
    val reviewed: String,
    val studyTime: String,
    val learningProgress: String,
    val last7Days: String,
    val accuracy: String,
    val general: String,
    val language: String,
    val theme: String,
    val systemDefault: String,
    val light: String,
    val dark: String,
    val auto: String,
    val llmApiConfig: String,
    val apiBaseUrl: String,
    val apiKey: String,
    val modelName: String,
    val wordBooks: String,
    val newWordBook: String,
    val bookName: String,
    val descriptionOptional: String,
    val create: String,
    val noWordBooks: String,
    val about: String,
    val aboutText: String,
    val loading: String,
    val preparingQuiz: String,
    val pasteTextHint: String,
    val targetLanguageHint: String,
    val parseWithAI: String,
    val parsing: String,
    val addToBook: String,
    val noBookGeneral: String,
    val selectAll: String,
    val deselect: String,
    val importComplete: String,
    val importMore: String,
    val importNWords: String,
    val parsedNWords: String,
    val selectFile: String,
    val showKey: String,
    val hideKey: String,
    val english: String,
    val chinese: String,
    val successfullyImported: String,
    val orPasteManually: String,
    val moveToBook: String,
    val selectBookToMove: String,
    val selected: String,
    val changeFile: String,
    val reParse: String,
    val addProfile: String,
    val editProfile: String,
    val newProfile: String,
    val removeFromBook: String,
    val reviewOptions: String,
    val reviewModeLabel: String,
    val countLabel: String,
    val countHint: String,
    val start: String,
    val clearRecords: String,
    val clearRecordsMsg: String,
    val createNew: String,
    val select: String,
    val exportBook: String
)

val EnglishStrings = UiStrings(
    appName = "Vocabuilder",
    search = "Search",
    closeSearch = "Close search",
    clear = "Clear",
    importWords = "Import words",
    importWordBookJson = "Import Word Book (JSON)",
    settings = "Settings",
    allWords = "All Words",
    wordBook = "Word Book",
    searchWords = "Search words...",
    noWords = "No words yet",
    noMatching = "No matching words",
    tapPlusToAdd = "Tap + to add your first word",
    tryDifferentSearch = "Try a different search term",
    review = "Review",
    quiz = "Quiz",
    stats = "Stats",
    learned = "Learned",
    addWord = "Add Word",
    editWord = "Edit Word",
    wordTerm = "Word / Term",
    definitionTrans = "Definition / Translation",
    exampleSentence = "Example Sentence (optional)",
    categoryOptional = "Category (optional)",
    notesOptional = "Notes (optional)",
    save = "Save",
    cancel = "Cancel",
    delete = "Delete",
    back = "Back",
    flashcardReview = "Flashcard Review",
    tapToReveal = "Tap to reveal",
    howWell = "How well did you know this?",
    forgot = "Forgot",
    hard = "Hard",
    good = "Good",
    easy = "Easy",
    skip = "Skip",
    allCaughtUp = "All caught up!",
    noWordsToReview = "No words to review right now.\nAdd more words or check back later.",
    reviewComplete = "Review Complete!",
    known = "Known",
    reviewAgain = "Review Again",
    takeQuiz = "Take Quiz",
    goBack = "Go Back",
    notEnoughWords = "Not enough words",
    needAtLeast4 = "You need at least 4 words to take a quiz.",
    question = "Question",
    score = "Score",
    quizComplete = "Quiz Complete!",
    viewResults = "View Results",
    retryQuiz = "Retry Quiz",
    nextQuestion = "Next Question",
    finishQuiz = "Finish Quiz",
    whatIsMeaning = "What is the meaning of",
    excellent = "Excellent!",
    greatJob = "Great job!",
    goodEffort = "Good effort!",
    keepPracticing = "Keep practicing!",
    tryAgain = "Try Again",
    backToHome = "Back to Home",
    statistics = "Statistics",
    totalWords = "Total Words",
    learnedWords = "Learned",
    reviewed = "Reviewed",
    studyTime = "Study Time",
    learningProgress = "Learning Progress",
    last7Days = "Last 7 Days",
    accuracy = "Accuracy",
    general = "General",
    language = "Language",
    theme = "Theme",
    systemDefault = "System",
    light = "Light",
    dark = "Dark",
    auto = "Auto",
    llmApiConfig = "LLM API Configuration",
    apiBaseUrl = "API Base URL",
    apiKey = "API Key",
    modelName = "Model Name",
    wordBooks = "Word Books",
    newWordBook = "New Word Book",
    bookName = "Book Name",
    descriptionOptional = "Description (optional)",
    create = "Create",
    noWordBooks = "No word books. Create one to organize your vocabulary.",
    about = "About",
    aboutText = "Vocabuilder\nVersion 1.0\nAn intelligent vocabulary learning app with spaced repetition and AI-powered word extraction.",
    loading = "Loading...",
    preparingQuiz = "Preparing quiz...",
    pasteTextHint = "Paste text or word list here",
    targetLanguageHint = "Target language (optional)",
    parseWithAI = "Parse with AI",
    parsing = "Parsing...",
    addToBook = "Add to book",
    noBookGeneral = "No book (general)",
    selectAll = "Select All",
    deselect = "Deselect",
    importComplete = "Import Complete!",
    importMore = "Import More",
    importNWords = "Import %d Words",
    parsedNWords = "Parsed %d words",
    selectFile = "Select File",
    showKey = "Show key",
    hideKey = "Hide key",
    english = "English",
    chinese = "中文",
    successfullyImported = "Successfully imported %d words.",
    orPasteManually = "Or paste text manually:",
    moveToBook = "Move to Book",
    selectBookToMove = "Select a book to move %d words to:",
    selected = "selected",
    changeFile = "Change File",
    reParse = "Re-parse",
    addProfile = "Add Profile",
    editProfile = "Edit Profile",
    newProfile = "New Profile",
    removeFromBook = "Remove from book",
    reviewOptions = "Review Options",
    reviewModeLabel = "Review mode:",
    countLabel = "Count:",
    countHint = "Count (empty = all)",
    start = "Start",
    clearRecords = "Clear Records",
    clearRecordsMsg = "Clear all study records? This will erase review history and study time. Word data will be preserved.",
    createNew = "Create New",
    select = "Select",
    exportBook = "Export Word Book (JSON)"
)

val ChineseStrings = UiStrings(
    appName = "Vocabuilder",
    search = "搜索",
    closeSearch = "关闭搜索",
    clear = "清除",
    importWords = "导入单词",
    importWordBookJson = "导入单词本（JSON）",
    settings = "设置",
    allWords = "全部单词",
    wordBook = "单词本",
    searchWords = "搜索单词...",
    noWords = "还没有单词",
    noMatching = "没有匹配的单词",
    tapPlusToAdd = "点击 + 添加第一个单词",
    tryDifferentSearch = "尝试其他搜索词",
    review = "复习",
    quiz = "测验",
    stats = "统计",
    learned = "已掌握",
    addWord = "添加单词",
    editWord = "编辑单词",
    wordTerm = "单词 / 术语",
    definitionTrans = "释义 / 翻译",
    exampleSentence = "例句（可选）",
    categoryOptional = "分类（可选）",
    notesOptional = "笔记（可选）",
    save = "保存",
    cancel = "取消",
    delete = "删除",
    back = "返回",
    flashcardReview = "闪卡复习",
    tapToReveal = "点击查看释义",
    howWell = "你掌握得怎么样？",
    forgot = "忘了",
    hard = "困难",
    good = "不错",
    easy = "简单",
    skip = "跳过",
    allCaughtUp = "全部完成！",
    noWordsToReview = "暂时没有需要复习的单词。\n添加更多单词或稍后再来。",
    reviewComplete = "复习完成！",
    known = "已掌握",
    reviewAgain = "再次复习",
    takeQuiz = "开始测验",
    goBack = "返回",
    notEnoughWords = "单词不足",
    needAtLeast4 = "至少需要 4 个单词才能进行测验。",
    question = "题目",
    score = "得分",
    quizComplete = "测验完成！",
    viewResults = "查看结果",
    retryQuiz = "重新测验",
    nextQuestion = "下一题",
    finishQuiz = "完成测验",
    whatIsMeaning = "以下单词的含义是：",
    excellent = "太棒了！",
    greatJob = "做得不错！",
    goodEffort = "继续加油！",
    keepPracticing = "坚持练习！",
    tryAgain = "再试一次",
    backToHome = "返回首页",
    statistics = "学习统计",
    totalWords = "总单词数",
    learnedWords = "已掌握",
    reviewed = "已复习",
    studyTime = "学习时间",
    learningProgress = "学习进度",
    last7Days = "最近 7 天",
    accuracy = "正确率",
    general = "通用",
    language = "语言",
    theme = "主题",
    systemDefault = "跟随系统",
    light = "浅色",
    dark = "深色",
    auto = "自动",
    llmApiConfig = "LLM API 配置",
    apiBaseUrl = "API 地址",
    apiKey = "API 密钥",
    modelName = "模型名称",
    wordBooks = "单词本",
    newWordBook = "新建单词本",
    bookName = "单词本名称",
    descriptionOptional = "描述（可选）",
    create = "创建",
    noWordBooks = "还没有单词本。创建一个来整理你的词汇。",
    about = "关于",
    aboutText = "单词本\n版本 1.0\n一款智能背单词应用，支持间隔重复和 AI 单词提取。",
    loading = "加载中...",
    preparingQuiz = "准备测验中...",
    pasteTextHint = "在此粘贴文本或单词列表",
    targetLanguageHint = "目标语言（可选）",
    parseWithAI = "AI 解析",
    parsing = "解析中...",
    addToBook = "添加到单词本",
    noBookGeneral = "不指定（通用）",
    selectAll = "全选",
    deselect = "取消选择",
    importComplete = "导入完成！",
    importMore = "继续导入",
    importNWords = "导入 %d 个单词",
    parsedNWords = "已解析 %d 个单词",
    selectFile = "选择文件",
    showKey = "显示密钥",
    hideKey = "隐藏密钥",
    english = "English",
    chinese = "中文",
    successfullyImported = "成功导入 %d 个单词。",
    orPasteManually = "或手动粘贴文本：",
    moveToBook = "移动到单词本",
    selectBookToMove = "选择要移动 %d 个单词到的单词本：",
    selected = "已选择",
    changeFile = "更换文件",
    reParse = "重新解析",
    addProfile = "添加配置",
    editProfile = "编辑配置",
    newProfile = "新建配置",
    removeFromBook = "从词本移除",
    reviewOptions = "复习选项",
    reviewModeLabel = "复习模式：",
    countLabel = "数量：",
    countHint = "数量（留空=全部）",
    start = "开始",
    clearRecords = "清除记录",
    clearRecordsMsg = "清除所有学习记录？这将删除复习历史和统计，但单词数据会保留。",
    createNew = "新建",
    select = "选择",
    exportBook = "导出单词本（JSON）"
)

val LocalUiStrings = compositionLocalOf { EnglishStrings }
